---
title: "MAUI Presentation Outline"
author: "Garrett Jaeger & Zach Burns"
date: "April 1, 2019"
output:
  pdf_document: default
  word_document:
    reference_docx: word-styles-default.docx
  html_document: default
---

```{r setup, include=FALSE, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library(plotly)
```

<<<<<<< HEAD
1. Intro
    + Looking for novelty and usefulness (Runco & Jaeger)
      - approaches to orignality
        * not in the most common list (TTCT)
        * Statistical infrequency
        * consensual assessment (Amabile)
          + Individual Ideas
          + Ideational Pool (Runco)
      - usefulness is personally meaningful
        * _not_ the focus of our studies
    + Outcomes and Process
      - From assessment to behavioral coding (Bonawitz et al)
      - Developmental methodologies (Adolph)
    + Research Questions
      - How does the originality of ideas fluctuate during DT?
      - Can we provide more information about the creativity of an individual?
      - How else can we observe children's creativity?
2. Revising the Uniqueness Index
=======
## Problem statement
* Take as given the standardized answer set to an open-ended creativity task
* One might predict that response freqency takes one of two shapes:
  + More frequently given responses make up a large proportion of all responses, less frequently given responses make up a small proportion
    - (Possible underlying process: responses are ordered, people generate the responses in order, more creative individuals can get through more of the order)
  + Less frequently given responses make up a large proportion of all responses, more frequently given responses make up a small proportion
    - (possible underlying process: ???)
* For a variety of reasons, a standardized answer sets tend to take the latter shape

## Presentation Outline
1. Standard definition suggests that we look for both novelty and usefulness
    + approaches to orignality
      - not in the most common list (TTCT)
      - Statistical infrequency
      - consensual assessment (Amabile)
        * Individual Ideas
        * Ideational Pool
    + usefulness is personal
2. Revising the Uniqueness Index

The standardly ue

>>>>>>> b7c75aa41f38976b17cb88a4d62a69510e97a87e
    + Its usefulness
      - Less subjective
      - Thresholds create dichotomous tally to compare with other indices (fluency, flexibility)
    + Its issues
      - Unclear reasoning behind thresholds
      - Sample dependency
      - Overestimating originality
      - Resulting tallies are highly correlated with fluency
    + MAUI
<<<<<<< HEAD
      - Acknowledging levels as unit of analysis
        * Response
        * Item
        * Individual
        * Sample
      - Non-parametric rank distribution density of ideas attributed to item prompt
        * approach similar to Item Response Theory, where score represents the participant's ability and the item difficulty
      - Marketplace of ideas
        * identifying the best ideas
=======
      - acknowledging levels as unit of analysis
      - distribution of ideas are attributed to item prompt
>>>>>>> b7c75aa41f38976b17cb88a4d62a69510e97a87e
3. Process Analyses
    + Continuous MAUI
      - _how_ original is an idea?
    + Ideational Profiles
      - revisiting the "order effect" (Torrance; Silvia et al)
      - Discriminating different approaches/strategies
    + Shift Strategy >> episodic divergence
<<<<<<< HEAD
      - adding granularity to divergence after lexical shifts (Acar & Runco)
4. Exploratory Play
    + Curiosity and learning (Legare & Lombrowski)
=======
      - adding granularity to divergence after lexical shifts
4. Exploratory Play
    + Curiosity and learning
>>>>>>> b7c75aa41f38976b17cb88a4d62a69510e97a87e
    + Affordances
    + Troubleshooting and persistence
5. Reflections on the Advancements and Flexibility of MAUI
    + A better UI
    + Profile as additional perpective
    + Any prompt will do...
    + Reduced number of prompts
    